# GraphQL Tools and Servlet Configuration  
graphql:
  extended-scalars: Date
  tools:
    schemaLocationPattern: "**/*.graphql"
  servlet:
    mapping: /graphql
    enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
    exception-handlers-enabled: true 
    maxQueryDepth: 100
    maxQueryComplexity: 100
    async-timeout: 5000
      
## H2 & Data Source Configuration 
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:airlinedb;DB_CLOSE_ON_EXIT=FALSE 
  profiles:    active:#    - security
  security:
    oauth2:
      resourceserver:
        jwt: 
          public-key-location: public-key.txt
         
## Port Configuration 
server:
  port: 4000
  