# GraphQL Tools and Servlet Configuration  
graphql:
  tools:
    schemaLocationPattern: "**/*.graphql"
  servlet:
    mapping: /graphql
    enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
    exception-handlers-enabled: true 
    maxQueryDepth: 100
    maxQueryComplexity: 100
    async-timeout: 5000
    
  playground:    enabled: true
    
## H2 & Data Source Configuration 
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:airlinedb;DB_CLOSE_ON_EXIT=FALSE 
  profiles:    active:#    - security
  security:
    oauth2:
      resourceserver:
        jwt: 
          public-key-location: public-key.txt
      
## Actuator  
management:
  endpoints: 
    enabled-by-default: true
    web:
      exposure:
        include: "*"
           
## Port Configuration 
server:
  port: 4000

## Log GraphQL Debug Information for better understanding
logging:
  level:
    '[graphql]': debug
    
## Enable Long Request to messure the performance optimization     
thinkenterprise:
  longRequest:
    enable: true

  