# GraphQL Tools and Servlet Configuration  
graphql:
  tools:
    schema-location-pattern: "**/*.graphql"
    introspection-enabled: true
  servlet:
    enabled: true
    mapping: /graphql
  playground:
    enabled: true
  
## H2 & Data Source Configuration 
spring: 
  h2:
    console:
      enabled: true
      path: /h2-console    
  datasource:
    url: jdbc:h2:mem:airlinedb;DB_CLOSE_ON_EXIT=FALSE 
        
## Port Configuration 
server:
  port: 4000
  