# GraphQL Tools and Servlet Configuration  
graphql:
  tools:
    schemaLocationPattern: "**/*.graphql"
    introspection-enabled: true
  servlet:
    enabled: true
    mapping: /graphql
  playground:
    enabled: true          
## Port Configuration 
server:
  port: 4000
  
